POST http://localhost:8000/api/transactions/
Content-Type: application/json

{
  "text": "Salary December",
  "amount": 21000.00
}

###

GET http://localhost:8000/api/transactions/

###
DELETE http://localhost:8000/api/transactions/3c75314a-8e57-4820-bc7e-fb75a99adf00/

###
PUT http://localhost:8000/api/transactions/5687c0d9-c85c-48c8-99bd-ec1c893eb0af/
Content-Type: application/json

{
  "text": "Updated Salary December",
  "amount": 25000.00
}

###
PATCH http://localhost:8000/api/transactions/5687c0d9-c85c-48c8-99bd-ec1c893eb0af/
Content-Type: application/json

{
  "amount": 23500.00
}